name       : mrrescue
version    : 1.02e
release    : 3
source     :
    - git|https://github.com/SimonLarsen/mrrescue.git : 1.02e
license    :
    - BSD-3-Clause
    - CC-BY-SA-3.0
component  : games.platformer
summary    : Mr. Rescue is an arcade styled 2d action game centered around evacuating civilians from burning buildings.
description: |
    Mr. Rescue is an arcade styled 2d action game centered around evacuating civilians from burning buildings.
rundeps    :
    - love
build      : |
    zip mrrescue.zip -r *
install    : |
    install -D -m 00644 $pkgfiles/mrrescue.desktop $installdir/usr/share/applications/mrrescue.desktop
    install -D -m 00644 mrrescue.zip $installdir/usr/share/mrrescue/mrrescue.love
